### ISSUE TITLE
schema edits for MDTF interoperability

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [NOAA-GFDL/CatalogBuilder#10]
Following this https://github.com/NOAA-GFDL/MDTF-diagnostics/issues/588, this issue tracks the following changes to the schema 

Change: modeling_realm to realm (GFDL Catalog Builder)
Change: temporal_subset to time_range (GFDL Catalog Builder)
Add: standard_name (GFDL Catalog Builder)

**Comment by ceblanton** [comment]
This is already fixed, isn't it?

https://github.com/NOAA-GFDL/CatalogBuilder/blob/main/catalogbuilder/cats/gfdl_template.json

**Comment by aradhakrishnanGFDL** [comment]
> This is already fixed, isn't it?
> 
> https://github.com/NOAA-GFDL/CatalogBuilder/blob/main/catalogbuilder/cats/gfdl_template.json

Yes, but just the json seemed to updated. We need sample config yaml files and the test configs in CI also to be updated which is now done.

**Comment by aradhakrishnanGFDL** [comment]
standard_name addition is pending. @Ciheim this PR will add an empty column that you will fill in your feature addition, or want your PR to take care of that as well?
