### ISSUE TITLE
"time_range" is a required 'groupby_attr'

### ISSUE THREAD

**Issue by jtmims** [NOAA-GFDL/CatalogBuilder#28]
ESM-intake is currently not able to supply needed information to the MDTF framework. I found that 'time_range' is required in the groupby_attrs section of the header json file of the catalog. The inclusion of this allows the catalog to run on the MDTF.

i.e.:
`"groupby_attrs": [
      "source_id",
      "experiment_id",
      "frequency",
      "table_id",
      "grid_label",
      "realm",
      "member_id",
      "chunk_freq",
      "time_range"
    ],
`

**Comment by aradhakrishnanGFDL** [comment]
@jtmims here is a catalog with this addition, though adding time_range to aggregation cols does not seem ideal. You can still test the catalog with MDTF for the current needs and I have a PR in the pipeline. Hope this helps.  

/home/a1r/github/noaa-gfdl/catalogs/c96L65_am5f7b10r0_amip30_0806.json
