### ISSUE TITLE
Request for catalog combining tool

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/CatalogBuilder#56]
### Discussed in https://github.com/NOAA-GFDL/CatalogBuilder/discussions/50

<div type='discussions-op-text'>

<sup>Originally posted by **apreucil** August 29, 2024</sup>
I am confused if the catalogs are meant to be unique per model run or if they can and should be combined. This would greatly change the way analysis scripts are created if multiple catalogs are needed to perform an analysis between several model runs. My question is how to combine catalogs if that is indeed an intended use of this tool?</div>

**Comment by aradhakrishnanGFDL** [comment]
One of the first examples we demonstrated with our catalog builder and the MDTF is a catalog that was combined from two experiments.  @Ciheim did this manually. 
To me, this sounds like a validator dependency (priority) to ensure combining requirements are "Valid" and then do a simple concatenation ( by the user at the initial stage while the tool has the --combine support)

See [https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/diagnostics/example_multicase/amip_c96L65_am5f3b1r0_pdclim1850F_combined.json](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/diagnostics/example_multicase/amip_c96L65_am5f3b1r0_pdclim1850F_combined.json)

The MDTF example notebook uses that 
https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/diagnostics/example_multicase/example_multirun_demo.ipynb

**Comment by aradhakrishnanGFDL** [comment]
Usage 

```
combine_cats.py --help
Usage: combine_cats.py [OPTIONS]

  This script combines two json catalogs. It takes the path to input catalogs
  and the output catalog names as input. The options may be passed with this
  as the template:  combine_catalogs.py -i jsoncatalog -i jsoncatalog2 -o
  outputjson

  Example usage: combine_cats.py -i /home/a1r/github/noaa-
  gfdl/catalogs/CM4.5v01_om5b06_piC_noBLING.json -i /home/a1r/github/noaa-
  gfdl/catalogs/ESM4.5v01_om5b04_piC.json -o combinedcat.json

Options:
  -i, --inputfiles TEXT   Pass json catalog files to-be-combined, space
                          separated  [required]
  -o, --output_path TEXT  Specify the output json path  [required]
  --help                  Show this message and exit.
```
