### ISSUE TITLE
ua200 does not have 'standard_name' populated

### ISSUE THREAD

**Issue by jtmims** [NOAA-GFDL/CatalogBuilder#77]
**Describe the bug**
For some level-extraction variables (i.e. ua200 and ua850), the 'standard_name' col is not populated. This makes it impossible for the MDTF to grab the data even though it exists in the catalog.  After an ncdump, the standard_name is found in the .nc file. If there is anything I can do to help, please let me know!

**Comment by aradhakrishnanGFDL** [comment]
Hi @jtmims, The builder does not look up the netcdf file for this particular column in the default form. 

Add the variable mapping (e.g. ua200 as the GFDL_varname and the corresponding standard name. If there is an equivalent cmor_varname such as uas, you can add that as well) to this [csv](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/data/gfdl-cmor-tables/gfdl_to_cmip5_vars.csv) in the MDTF repository. Let me know if doing this and re-running the catalog builder resolves the issue.

**Comment by jtmims** [comment]
Hi @aradhakrishnanGFDL, thank you for the quick reply! In my own hubris, I forgot that the catalog builder is netcdf agnostic by default. I blame my bad sinuses this week. I updated the csv files you pointed to. After some further digging, it seems as though some links to those files had to be updated to point towards the MDTF repo main branch. Hopefully, this will fix things up!

**Comment by aradhakrishnanGFDL** [comment]
> Hi @aradhakrishnanGFDL, thank you for the quick reply! In my own hubris, I forgot that the catalog builder is netcdf agnostic by default. I blame my bad sinuses this week. I updated the csv files you pointed to. After some further digging, it seems as though some links to those files had to be updated to point towards the MDTF repo main branch. Hopefully, this will fix things up!

Thanks for the fix! It's merged in now.
