### ISSUE TITLE
non-CMIP style output structure and variable names

### ISSUE THREAD

**Issue by tmerlis** [NOAA-GFDL/CatalogBuilder#91]
I want to use CatalogBuilder to make a data catalog for X-SHiELD output. The model output does not follow CMIP style in (at least) two ways.

The structure of the netcdf output is 
/scratch/cimes/GLOBALFV3/stellar_run/processed/20191020.00Z.C3072.L79x2_pire_PLUS_4K/pp/2020082000/liq_wat_C3072_1440x720.fre.nc

/A/B/C/D/E/F/experiment/pp/date/${var_name}_resolutionDetails.nc

1. The variable names are not standard CMIP names. This seemed to produce an error:

File ~/.conda/envs/catalogbuilder/lib/python3.13/site-packages/catalogbuilder/scripts/gen_intake_gfdl.py:112, in create_catalog(input_path, output_path, config, filter_realm, filter_freq, filter_chunk, overwrite, append, slow, verbose) 
110 list_variable_id = df["variable_id"].unique().tolist() 
111 list_realm = df["realm"].unique().tolist()
--> 112 dictVarCF = getinfo.getStandardName(list_variable_id,list_realm) 
113 #print("standard name from look-up table-", dictVarCF) 
114 for k, v in dictVarCF.items():

2. The time chunking is irregular. The dates in YEARMONDAY format and may have a different number of days.

---

Here's the relevant part of my config yaml from the attempt that produced the error above:

output_path_template: ['NA','NA','source_id','NA','NA',experiment_id','custom_pp','time_range']

output_file_template: ['time_range','variable_id']

#######################################################

input_path:  "/scratch/cimes/GLOBALFV3/stellar_run/processed/20191020.00Z.C3072.L79x2_pire/pp/"

Let me know if there are other details that would be helpful.

Thank you!
-Tim

**Comment by aradhakrishnanGFDL** [comment]
@tmerlis thanks for opening an issue regarding this. 

Try this and see what happens in your config

output_file_template: ['variable_id','NA']

**Comment by tmerlis** [comment]
Hi @aradhakrishnanGFDL,

I updated my config as you suggested and I get the same specific L112 issue:

File ~/.conda/envs/catalogbuilder/lib/python3.13/site-packages/catalogbuilder/scripts/gen_intake_gfdl.py:112, in create_catalog(input_path, output_path, config, filter_realm, filter_freq, filter_chunk, overwrite, append, slow, verbose)
    110 list_variable_id = df["variable_id"].unique().tolist()
    111 list_realm = df["realm"].unique().tolist()
--> 112 dictVarCF = getinfo.getStandardName(list_variable_id,list_realm)

Is there a way to have verbose output to see what the path it is trying to use? In other words, to confirm it is failing because of the standard name vs. a more basic issue with the file path.

Thank you!
-Tim

**Comment by aradhakrishnanGFDL** [comment]
Yes, you can pass verbose=True to the create_catalog(). If you’re running gen_intake_gfdl, I think it’s —verbose 

It looks like realm is not in the path and no way to get it. That particular bit relies on that, and needs a better way of handling the exception. 

Two things you can try as a workaround 

1- remove standard_name from the header_list in the config file. 

Or 

2- though incorrect , assign one of the directories to point to realm for the sake of the test. (In your output_path_template, perhaps the second or fourth NA can be “realm” for the test)

If these don’t help, I’ll give it a shot by Monday. I think it’s a minor issue either way. The file name there isn’t cmip or GFDL ish so it looks like a good use case to explore. Thanks

**Comment by tmerlis** [comment]
Hi @aradhakrishnanGFDL,

Your suggestion 1. worked very smoothly!

I now have built a catalog and have used it successfully to make a simple plot, following this existing notebook (https://nbviewer.org/github/aradhakrishnanGFDL/canopy-cats/blob/main/notebooks/om_example.ipynb). 

I will upload my two ipynb soon. 

Thank you so much---I think this is powerful for improving X-SHiELD workflows. 
-Tim
